repro:
  seed: 42
  tf_deterministic: true

data:
  path: data
  features: sensors_only
  seq_len: 80
  stride: 1
  label_mode: any
  label_dilation: 3
  anomaly_horizon: 30
  scale: standard
  scale_fit_on: train_normals_only
  drop_low_variance_threshold: 1e-6
  drop_sensors: ["s01","s05","s10","s16","s18","s19"]
  unitwise: true

splits:
  train_frac: 0.8   # or whatever you used before
  seed: 42

training_lstm:
  enc1: 128
  enc2: 64
  latent: 32
  dropout: 0.2
  batch: 64
  epochs: 100
  lr: 5.0e-3
  loss: mse            # <- we’re using MSE now
  huber_delta: 1.0
  val_frac: 0.10
  early_stopping_patience: 10
  early_stopping_min_delta: 1e-4
  rlr_patience: 5

evaluation:
  threshold: val_percentile     # was val_percentile
  val_percentile: 98.5     # start here
  smooth_kernel: 0
  agg_window: 1
  min_run_length: 3
  per_unit_threshold: false
